version: '3.4'
services:
  internet_test:
    container_name: internet_test
    build:
      context: .
      dockerfile: ./dockerfiles/speed.dockerfile
    restart: unless-stopped
    environment:
      INTERVAL: ${INTERVAL:-3600}
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_INIT_BUCKET: speedtest
      INFLUXDB_INIT_ORG: internet-auto-tester
      SERVER_ID: ${SERVER_ID}
      INFLUX_TOKEN: ${INFLUX_TOKEN}

  db:
    image: influxdb
    container_name: db_influxs
    volumes:
      - ../resources-internet-speed-test/influx/:/root/.influxdbv2
    ports:
      - '8083:8083'
      - '8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: internet-auto-tester
      DOCKER_INFLUXDB_INIT_BUCKET: speedtest
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
