version: '3.4'
services:
  internet_test:
    container_name: internet_test
    build:
      context: .
      dockerfile: ./dockerfiles/speed.dockerfile
    restart: unless-stopped
    environment:
      INTERVAL: ${INTERVAL:-3600}
      SERVER_ID: ${SERVER_ID:-None}

  db:
    image: influxdb
    container_name: db_influx
    volumes:
      - ../resources/influx/:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_DB: speedtest
